const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const main = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8')
const captureDomain = fs.readFileSync(path.join(__dirname, '..', 'main/domains/capture/index.js'), 'utf8')
const recordDomain = fs.readFileSync(path.join(__dirname, '..', 'main/domains/record/index.js'), 'utf8')
const searchDomain = fs.readFileSync(path.join(__dirname, '..', 'main/domains/search/index.js'), 'utf8')
const selectionDomain = fs.readFileSync(path.join(__dirname, '..', 'main/domains/selection/index.js'), 'utf8')
const preload = fs.readFileSync(path.join(__dirname, '..', 'preload.js'), 'utf8')
const config = fs.readFileSync(path.join(__dirname, '..', 'config', 'config.js'), 'utf8')

test('game mode is persisted and synchronizes tray, shortcuts, selection, and search', () => {
  assert.match(main, /system:\s*\{[\s\S]*gameMode: false/)
  assert.match(main, /settingsService\.updateSettings\(\{ system: \{ gameMode: nextEnabled \} \}\)/)
  assert.match(main, /function applyGameModeState\([\s\S]*registerShortcuts\(\)[\s\S]*selectionDomain\.applyGameMode\(gameMode\)[\s\S]*searchDomain\.hideSearchWindow\(\)/)
  assert.match(selectionDomain, /function applyGameMode\(gameMode\) \{[\s\S]*hookService\?\.suspend\('game-mode'\)[\s\S]*hideToolbar\(\)/)
  assert.match(selectionDomain, /if \(isGameModeEnabled\(\)\) return hookService\.suspend\('game-mode'\)/)
  assert.match(selectionDomain, /\['resume',[\s\S]*if \(!isGameModeEnabled\(\)\) hookService\?\.notePowerEvent\('wake', 'system-resume'\)/)
  assert.match(main, /tray\.setContextMenu\(Menu\.buildFromTemplate\(buildTrayMenuTemplate\(\{/)
  assert.match(main, /webContents\.send\('app:game-mode-changed', gameMode\)/)
  assert.match(preload, /onGameModeChanged:[\s\S]*ipcRenderer\.on\('app:game-mode-changed'/)
  assert.match(config, /switchMarkup\(settings\.system\.gameMode, 'gameMode', 'system'\)/)
  assert.match(config, /onGameModeChanged\(\(enabled\) =>/)
})

test('game mode guards every feature dispatch and passive summon entry point', () => {
  assert.match(main, /async function executeFunction\(name, payload = \{\}\) \{\s*assertGameModeDisabled\(\)/)
  assert.match(captureDomain, /async function createCaptureWindow\(options = \{\}\) \{\s*assertGameModeDisabled\(\)/)
  assert.match(searchDomain, /function createSearchWindow\(\) \{\s*assertGameModeDisabled\(\)/)
  assert.match(recordDomain, /async function createRecordWindow\(options = \{\}\) \{\s*assertGameModeDisabled\(\)/)
  assert.match(selectionDomain, /function handleTextSelection\(data\) \{\s*if \(isGameModeEnabled\(\)\)/)
})
