const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const html = fs.readFileSync(path.join(root, 'config', 'config.html'), 'utf8')
const script = fs.readFileSync(path.join(root, 'config', 'config.js'), 'utf8')
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8')
const router = fs.readFileSync(path.join(root, 'main', 'services', 'ai-feature-router.js'), 'utf8')
const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8')

test('config app exposes the model provider route with provider and feature-model subpages', () => {
  assert.match(html, /data-route="models"/)
  assert.match(script, /function renderModels\(\)/)
  assert.match(script, /data-models-tab="providers"/)
  assert.match(script, /data-models-tab="features"/)
  assert.match(script, /功能模型/)
  assert.match(script, /data-expand-provider=/)
  assert.match(script, /data-provider-editor=/)
  assert.match(script, /data-provider-name/)
  assert.match(script, /data-provider-base-url/)
  assert.match(script, /data-provider-protocol/)
  assert.match(script, /data-provider-api-key/)
  assert.match(script, /provider\.hasApiKey/)
  assert.match(script, /providerDraftWithSecret/)
  assert.match(script, /已配置——输入新值可替换/)
  assert.match(script, /data-restore-models=/)
  assert.match(script, /data-fetch-models=/)
  assert.match(script, /data-model-details=/)
  assert.match(script, /data-model-detail-panel=/)
  assert.match(script, /commitOpenProviderEditors\(\{ tolerant: true \}\)/)
  assert.match(script, /id="addModelProvider"/)
  assert.match(script, /id="saveProviderSettings"/)
  assert.match(script, /id="saveFeatureAssignments"/)
  assert.match(script, /data-feature-provider=/)
  assert.match(script, /markFeatureAssignmentsDirty/)
  assert.doesNotMatch(script, /select\.onchange = \(\) => void persistFeatureAssignments/)
  assert.match(script, /modelOptionsMarkup\(provider, '', feature\)/)
  assert.match(script, /data-provider-enabled/)
  assert.match(script, /data-feature-model/)
  assert.match(script, /toolbar:translate/)
  assert.match(script, /toolbar:explain/)
  assert.match(script, /ocr-translate/)
  assert.doesNotMatch(script, /modelProviderName/)
})

test('main process resolves feature assignments through the AI provider service', () => {
  assert.match(main, /require\('\.\/main\/services\/ai-providers'\)/)
  assert.match(main, /createToolbarActionStream/)
  assert.match(router, /resolveToolbarAiProvider\(settings, actionId\)/)
  assert.match(main, /resolveAiAssignment\(settings, 'chat'\)/)
  assert.match(main, /resolveAiAssignment\(settings, 'translation'\)/)
  assert.match(main, /resolveAiAssignment\(settings, 'ocr-translate'\)/)
  assert.match(main, /createMainWindow\('models'\)/)
})

test('preload fetches model catalogs through the existing secure test-connection channel', () => {
  assert.match(preload, /fetchProviderModels: \(provider\) => ipcRenderer\.invoke\('config:test-connection', \{ provider, fetchModels: true \}\)/)
  assert.doesNotMatch(preload, /config:get-api-key|config:save-api-key|config:start-hook/)
})
