const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const html = fs.readFileSync(path.join(__dirname, '..', 'config', 'config.html'), 'utf8')
const script = fs.readFileSync(path.join(__dirname, '..', 'config', 'config.js'), 'utf8')

test('config app exposes the selection toolbar route and controls', () => {
  assert.match(html, /data-route="selection-toolbar"/)
  assert.match(script, /function renderSelectionToolbarSettings\(/)
  assert.match(script, /id="searchEngine"/)
  assert.match(script, /id="translatePrompt"/)
  assert.match(script, /id="explainPrompt"/)
  assert.match(script, /id="translateSourceLanguage"/)
  assert.match(script, /id="translateTargetLanguage"/)
  assert.match(script, /翻译原语言/)
  assert.match(script, /翻译目标语言/)
  assert.match(script, /id="addCustomToolbar"/)
  assert.match(script, /剪贴板兼容模式/)
  assert.match(script, /switchMarkup\(toolbar\.clipboardFallback, 'clipboardFallback', 'selectionToolbar'\)/)
  assert.match(script, /data-custom-name/)
  assert.match(script, /data-custom-prompt/)
  assert.match(script, /data-delete-custom-toolbar/)
  assert.match(script, /data-move-toolbar/)
  assert.match(script, /draggable="true"/)
  assert.match(script, /ondrop/)
  for (const action of ['copy', 'search', 'translate', 'explain']) {
    assert.match(script, new RegExp(`${action}: \\{ label:`))
  }
})

test('main process normalizes toolbar settings and routes configured custom prompts', () => {
  const main = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8')
  const router = fs.readFileSync(path.join(__dirname, '..', 'main', 'services', 'ai-feature-router.js'), 'utf8')
  const deepseek = fs.readFileSync(path.join(__dirname, '..', 'deepseek.js'), 'utf8')
  const toolbar = fs.readFileSync(path.join(__dirname, '..', 'toolbar', 'toolbar.js'), 'utf8')
  const action = fs.readFileSync(path.join(__dirname, '..', 'action', 'action.js'), 'utf8')

  assert.match(main, /normalized\.selectionToolbar = normalizeSelectionToolbar/)
  assert.match(main, /enableClipboard: getSettings\(\)\.selectionToolbar\.clipboardFallback/)
  assert.match(main, /updateStartOptions\(\{ enableClipboard: settings\.selectionToolbar\.clipboardFallback \}\)/)
  assert.match(main, /consoleLike: app\.isPackaged \? null : console/)
  assert.match(main, /getVisibleToolbarActionDefinitions/)
  assert.match(main, /getToolbarActionDefinition\(toolbarConfig, action\)/)
  assert.match(main, /createToolbarActionStream\(\{ settings: currentSettings, action, text, requestOptions \}\)/)
  assert.match(router, /clients\.createTranslateStream\(provider, text, action\.prompt, languages, requestOptions\)/)
  assert.match(router, /settings\.selectionToolbar\?\.translateLanguages/)
  assert.match(router, /clients\.createExplainStream\(provider, text, action\.prompt, requestOptions\)/)
  assert.match(router, /clients\.createCustomStream\(provider, text, action\.prompt, requestOptions\)/)
  assert.match(main, /label: actionDefinition\.label/)
  assert.match(deepseek, /role: 'system', content: prompt/)
  assert.match(toolbar, /action\.label/)
  assert.match(toolbar, /toolbarAPI\.action\(action\.id\)/)
  assert.match(action, /const label = data\.label \|\| '解释'/)
})

test('selection toolbar appearance avoids a clipped rectangular shadow', () => {
  const manager = fs.readFileSync(path.join(__dirname, '..', 'main', 'services', 'selection-window-manager.js'), 'utf8')
  const toolbar = fs.readFileSync(path.join(__dirname, '..', 'toolbar', 'toolbar.html'), 'utf8')

  assert.match(manager, /createToolbarWindow\(\)[\s\S]*?hasShadow: false/)
  assert.match(toolbar, /\.toolbar \{[\s\S]*?box-shadow: inset/)
  assert.match(toolbar, /\.toolbar \{[\s\S]*?height: 40px/)
  assert.doesNotMatch(toolbar, /box-shadow: 0 4px 24px/)
})
