const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const main = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8')
const selectionDomain = fs.readFileSync(path.join(__dirname, '..', 'main', 'domains', 'selection', 'index.js'), 'utf8')
const action = fs.readFileSync(path.join(__dirname, '..', 'action', 'action.js'), 'utf8')
const deepseek = fs.readFileSync(path.join(__dirname, '..', 'main', 'services', 'ai', 'client.js'), 'utf8')
const adapters = fs.readFileSync(path.join(__dirname, '..', 'main', 'services', 'ai-protocol-adapters.js'), 'utf8')

test('main process rebuilds selection hooks across power and session transitions', () => {
  assert.match(selectionDomain, /const \{ SelectionHookService \} = require\('\.\.\/\.\.\/services\/selection-hook-service'\)/)
  assert.match(selectionDomain, /\['suspend', \(\) => hookService\?\.notePowerEvent\('sleep', 'system-suspend'\)\]/)
  assert.match(selectionDomain, /\['lock-screen', \(\) => hookService\?\.notePowerEvent\('sleep', 'lock-screen'\)\]/)
  assert.match(selectionDomain, /\['resume',[\s\S]*if \(!isGameModeEnabled\(\)\) hookService\?\.notePowerEvent\('wake', 'system-resume'\)/)
  assert.match(selectionDomain, /\['unlock-screen',[\s\S]*if \(!isGameModeEnabled\(\)\) hookService\?\.notePowerEvent\('wake', 'unlock-screen'\)/)
  assert.match(selectionDomain, /createUtilityProcessHostFactory/)
  const hookService = fs.readFileSync(path.join(__dirname, '..', 'main', 'services', 'selection-hook-service.js'), 'utf8')
  assert.match(hookService, /selection-hook-host\.js/)
  assert.match(main, /selectionDomain\.initSelectionHook\(\)\s*\n\s*selectionDomain\.registerSelectionPowerEvents\(\)/)
  assert.match(main, /selectionDomain\.disposeSelectionHook\(\)/)
})

test('toolbar streams use abortable sliding timeouts and sender ownership checks', () => {
  assert.match(selectionDomain, /new ToolbarStreamSession\(\{/)
  assert.match(selectionDomain, /const requestOptions = \{ signal: controller\.signal \}/)
  assert.match(selectionDomain, /armToolbarStreamTimeout\(controller\)[\s\S]*for await \(const chunk of stream\)/)
  assert.match(selectionDomain, /for await \(const chunk of stream\) \{[\s\S]*armToolbarStreamTimeout\(controller\)/)
  assert.match(selectionDomain, /isCurrentToolbarStreamSender\(event\)/)
  // Both rounds report a cancelled round before finalizing it, so a hidden window
  // cannot leave the renderer waiting for the 30s idle timeout.
  assert.match(selectionDomain, /finally \{\s*reportCancelledTurn\([\s\S]*?finishToolbarStream\(controller\)/)
  assert.match(deepseek, /createAiProtocolAdapter\(attempt, createClient\(attempt\)\)\.stream\([\s\S]*streamOptions\.requestOptions\)/)
  assert.match(adapters, /chat\.completions\.create\(buildChatStreamRequest\(config, messages, options\), requestOptions\)/)
  assert.match(action, /function armStreamTimeout\(\)/)
  assert.match(action, /actionBridge\.cancelStream\(conversation\.streamId\)/)
  assert.match(action, /onStreamData[\s\S]*armStreamTimeout\(\)/)
  assert.match(action, /onStreamReasoning[\s\S]*armStreamTimeout\(\)/)
})
